FROM localregistry.com/metabase/metabase:v0.53.2.2
RUN wget https://github.com/ClickHouse/metabase-clickhouse-driver/releases/download/1.53.1/clickhouse.metabase-driver.jar; \
    cp clickhouse.metabase-driver.jar /plugins;