namespace Api.Shared;

public static class LogHelpers
{
    public static (string message, object[] parameters) GetLog(HttpContext context, long elapsedMillis)
    {
        string message =
            "Generated by MainMiddleware: {api} - "
            + "Status Code: {status} - "
            + "Method: {method} - "
            + "Endpoint: {endpoint} - "
            + "Query String: {query} - "
            + "Requester: {user} - "
            + "Trace ID: {traceId} - "
            + "Execution Time: {elapsed}";
        object[] parameters = 
        [
            true,
            context.Response.StatusCode.ToString(),
            context.Request.Method,
            context.Request.Path,
            context.Request.QueryString,
            context.User.Identity?.Name ?? string.Empty,
            context.TraceIdentifier,
            elapsedMillis.ToString()
        ];

        return (message, parameters);
    }
}
