ARG CONFLUENT_VERSION

FROM registry-git.digikala.com/bi/rhodry/confluentinc/cp-kafka:${CONFLUENT_VERSION}

#  /home/appuser
RUN wget https://repo.maven.apache.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/1.0.0/jmx_prometheus_javaagent-1.0.0.jar
