version: "3.9"

x-network: &network
  networks:
    - platform

x-deploy-on-front: &deploy-on-front
  deploy:
    replicas: 1
    placement:
      constraints:
        - node.hostname == rhodrylab-01

services:
  postgres:
    image: postgres:14.15-alpine3.21
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    <<: *network
    <<: *deploy-on-front
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-h", "localhost", "-p", "5432"]
      interval: 10s
      timeout: 5s
      retries: 3

  prometheus:
    image: bitnami/prometheus:${PROMETHEUS_VERSION}
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prom_exporter/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
    networks:
      - app-tier
    depends_on:
      - kafka

secrets:
  postgres_password:
    external: true

volumes:
  postgres_data:
    driver: local

networks:
  platform:
    external: true