version: "3.9"

x-network: &network
  networks:
    - platform

x-deploy-on-front: &deploy-on-front
  deploy:
    replicas: 1
    placement:
      constraints:
        - node.hostname == ${HOSTNANME_01}

x-healthcheck-config: &healthcheck-config
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 40s

services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql.conf
    command: ["postgres", "-c", "config_file=/etc/postgresql.conf"] # to avoid overlap with postgresql.conf file bug error
    secrets:
      - postgres_password
    user: postgres
    <<: *deploy-on-front
    <<: *network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-h", "localhost", "-p", "5432"]
      <<: *healthcheck-config

  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION}
    ports:
      - ${PROMETHEUS_PORT}:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert-rules.yml:/etc/prometheus/alert-rules.yml
      - prometheus-data:/prometheus
    <<: *deploy-on-front
    <<: *network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      <<: *healthcheck-config

  alertmanager:
    image: prom/alertmanager:${ALERTMANAGER_VERSION}
    ports:
      - ${ALERTMANAGER_PORT}:9093
    volumes:
      - ./prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    <<: *deploy-on-front
    <<: *network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9093/-/healthy"]
      <<: *healthcheck-config

secrets:
  postgres_password:
    external: true

volumes:
  postgres-data:
    driver: local
  prometheus-data:
    driver: local

networks:
  platform:
    external: true