version: "3.9"

services:
  postgres:
    image: postgres:14.15-alpine3.21
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - platform
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-h", "localhost", "-p", "5432"]
      interval: 10s
      timeout: 5s
      retries: 3

secrets:
  postgres_password:
    external: true

volumes:
  postgres_data:
    driver: local

networks:
  platform:
    driver: overlay
    attachable: true




# deploy:
#   replicas: 2
#   update_config:
#     parallelism: 2
#     failure_action: rollback
#   placement:
#     constraints:
#       - 'node.role == worker'
#   restart_policy:
#     condition: on-failure
#     delay: 5s
#     max_attempts: 3
#     window: 120s

# networks:
#   front-tier:
#   back-tier:
#   payment:
#     driver: overlay
#     driver_opts:
#       encrypted: 'yes'