version: '3.7'

services:
  trino:
    image: registry-git.digikala.com/bi/biservices/trino
    deploy:
      placement:
        constraints:
          - node.hostname == rhodrylab-01
    networks:
      - rhodry_rhodry
    ports:
      - ${PORT}:8080
    configs:
      - source: logistics_catalog
        target: /etc/trino/catalog/kafka.properties

networks:
  rhodry_rhodry:
    external: true

configs:
  logistics_catalog:
    file: ./catalog/kafka.properties
