[[servers]]
# Ldap server host (specify multiple hosts space separated)
host = "bh-dc01.digikala.com"
# Default port is 389 or 636 if use_ssl = true
port = 636
# Set to true if LDAP server should use an encrypted TLS connection (either with STARTTLS or LDAPS)
use_ssl = true
# If set to true, use LDAP with STARTTLS instead of LDAPS
start_tls = false
# The value of an accepted TLS cipher. By default, this value is empty. Example value: ["TLS_AES_256_GCM_SHA384"])
# For a complete list of supported ciphers and TLS versions, refer to: https://go.dev/src/crypto/tls/cipher_suites.go
# tls_ciphers = []
# This is the minimum TLS version allowed. By default, this value is empty. Accepted values are: TLS1.1, TLS1.2, TLS1.3.
# min_tls_version = ""
# set to true if you want to skip SSL cert validation
ssl_skip_verify = true
# set to the path to your root CA certificate or leave unset to use system defaults
# root_ca_cert = "/run/secrets/LDAP_ROOT_CA_CERT"
# Authentication against LDAP servers requiring client certificates
# client_cert = "/path/to/client.crt"
# client_key = "/path/to/client.key"

# Search user bind dn
bind_dn = "CN=BI LDAP,OU=Digikala-ServiceAccount,OU=Digikala,OU=DKGroup,DC=digikala,DC=COM"
# bind_dn = "CN=%s,OU=Digikala-ServiceAccount,OU=Digikala,OU=DKGroup,DC=digikala,DC=COM"
# bind_dn = "CN=%s,OU=Data & Insight,OU=Technology,OU=Digikala-Users,OU=Digikala,OU=DKGroup,DC=digikala,DC=COM"
# Search user bind password
# If the password contains # or ; you have to wrap it with triple quotes. Ex """#password;"""
# bind_password = ""
# We recommend using variable expansion for the bind_password, for more info https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#variable-expansion
bind_password = "${BILDAP_PASS}"
# bind_password = "testbadpassword"

# Timeout in seconds. Applies to each host specified in the 'host' entry (space separated).
timeout = 10

# User search filter, for example "(cn=%s)" or "(sAMAccountName=%s)" or "(uid=%s)"
# Allow login from email or username, example "(|(sAMAccountName=%s)(userPrincipalName=%s))"
search_filter = "(|(sAMAccountName=%s)(UserPrincipalName=%s))"

# An array of base dns to search through
# search_base_dns = ["OU=Data & Insight,OU=Technology,OU=Digikala-Users,OU=Digikala,OU=DKGroup,DC=digikala,DC=COM", "OU=Digikala-ServiceAccount,OU=Digikala,OU=DKGroup,DC=digikala,DC=COM"]
search_base_dns = ["DC=digikala,DC=COM"]

# group_search_filter = "(&(objectClass=posixGroup)(memberUid=%s))"
# group_search_filter_user_attribute = "samaccountname"
group_search_base_dns = ["OU=DK-BI-Groups,OU=BI,OU=Enterprise Services,DC=digikala,DC=COM"]

# Specify names of the LDAP attributes your LDAP uses
[servers.attributes]
username = "sAMAccountName"
member_of = "memberOf"
email =  "UserPrincipalName"

[[servers.group_mappings]]
group_dn = "CN=HQ-BIDevops,OU=DK-BI-Groups,OU=BI,OU=Enterprise Services,DC=digikala,DC=COM"
org_role = "Admin"

[[servers.group_mappings]]
group_dn = "CN=HQ-BIManager,OU=DK-BI-Groups,OU=BI,OU=Enterprise Services,DC=digikala,DC=COM"
org_role = "Editor"

[[servers.group_mappings]]
group_dn = "CN=BILeaderTeam,OU=DK-BI-Groups,OU=BI,OU=Enterprise Services,DC=digikala,DC=COM"
org_role = "Editor"

[[servers.group_mappings]]
group_dn = "CN=HQ-BI-Grafana-Editors,OU=DK-BI-Groups,OU=BI,OU=Enterprise Services,DC=digikala,DC=COM"
org_role = "Editor"

[[servers.group_mappings]]
group_dn = "CN=HQ-BITeam,OU=DK-BI-Groups,OU=BI,OU=Enterprise Services,DC=digikala,DC=COM"
org_role = "Viewer"

[[servers.group_mappings]]
group_dn = "CN=HQ-BIService,OU=DK-BI-Groups,OU=BI,OU=Enterprise Services,DC=digikala,DC=COM"
org_role = "Viewer"
