global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "rabbitmq-server"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "rabbitmq:15692"

  - job_name: "rabbitmq-server-detailed"
    metrics_path: "/metrics/detailed"
    static_configs:
      - targets:
          - "rabbitmq:15692"
    params:
      family: ["queue_coarse_metrics"]
  
  - job_name: 'kafka'
    static_configs:
    - targets: ['kafka:7075']

rule_files:
  - alert-rules.yml

alerting:
  alertmanagers:
   - static_configs:
     - targets:
        - alertmanager:9093