---
  - name: installing pip
    hosts: all
    become: true
    tasks:
      - name: installing pip
        apt:
          name: python3-pip
          state: present

  - name: syncing server datetime with google
    hosts: all
    become: true
    tasks:
      - name: fetching datetime and syncing servers time
        shell: date -s "$(wget -qSO- --max-redirect=0 google.com 2>&1 | grep Date | cut -d' ' -f5-8)Z"
      - name: setting timezone to Asia/Tehran
        timezone:
          name: Asia/Tehran

  - name: installing docker
    hosts: all
    become: true
    tasks:
      - name: installing docker; sudo apt install docker.io=20.10.12-0ubuntu2~20.04.1
        apt:
          name: docker.io=20.10.12-0ubuntu2~20.04.1
          update_cache: true
          cache_valid_time: 86400
          state: present
      - name: adding user to docker group; sudo usermod -aG docker rhodry
        user:
          name: '{{ lookup("env", "USER") }}'
          state: present
          groups:
            - docker
          append: true
      - name: installing docker python module; pip install docker
        pip:
          name: docker

  - name: setting gitlab hostnames
    hosts: all
    become: true
    tasks:
      - name: adding gitlab.digikala.com to hosts; sudo echo -e "172.30.212.22 git.digikala.com\n" >> /etc/hosts
        lineinfile:
          path: '/etc/hosts'
          regexp: ' git.digikala.com'
          state: present
          line: '172.30.212.22 git.digikala.com'
      - name: adding registry-git.digikala.com to hosts; sudo echo -e "172.30.212.22 registry-git.digikala.com\n" >> /etc/hosts
        lineinfile:
          path: '/etc/hosts'
          regexp: 'registry-git.digikala.com'
          state: present
          line: '172.30.212.22 registry-git.digikala.com'

  - name: installing gitlab-runner
    hosts: front
    become: true
    tasks:
      - name: installing gitlab-runner; sudo apt update && apt install gitlab-runner
        apt:
          name: gitlab-runner
          update_cache: true
          cache_valid_time: 86400
          state: present
      - name: adding rhodry to gitlab-runner; sudo usermod -aG gitlab-runner rhodry
        user:
          name: '{{ lookup("env", "USER") }}'
          state: present
          groups:
            - gitlab-runner
          append: true
      - name: adding gitlab-runner to docker; sudo usermod -aG docker gitlab-runner
        user:
          name: 'gitlab-runner'
          state: present
          groups:
            - docker
          append: true

  - name: installing jq
    hosts: front
    become: true
    tasks:
      - name: installing jq; sudo apt update && apt install jq
        apt:
          name: jq
          update_cache: true
          cache_valid_time: 86400
          state: present
