---
  - name: logging into registry-git.digikala.com and pulling monitoring images
    hosts: all
    vars_prompt:
      - name: gitlab_user
        prompt: Enter GitLab User (dg email address without the @digikala.com)
      - name: gitlab_pass
        prompt: Enter GitLab Password (dg password)
    tasks:
      - name: logging into the registry; docker login registry-git.digikala.com
        docker_login:
          registry: registry-git.digikala.com
          username: "{{ gitlab_user }}"
          password: "{{ gitlab_pass }}"
      - name: pulling cadvisor
        docker_image:
          name: registry-git.digikala.com/bi/nevyn/cadvisor:0.44.0
          state: present
          source: pull
      - name: pulling node-exporter
        docker_image:
          name: registry-git.digikala.com/bi/nevyn/node-exporter:1.3.1
          state: present
          source: pull

  - name: pulling worker images
    hosts: workers_ramezani:workers_beheshti
    tasks:
      - name: zookeeper
        docker_image:
          name: registry-git.digikala.com/bi/rhodry/zookeeper
          state: present
          source: pull
      - name: kafka
        docker_image:
          name: registry-git.digikala.com/bi/rhodry/kafka
          state: present
          source: pull
      - name: connect
        docker_image:
          name: registry-git.digikala.com/bi/rhodry/connect
          state: present
          source: pull
      - name: jmx-exporter
        docker_image:
          name: registry-git.digikala.com/bi/nevyn/kafka-jmx-exporter
          state: present
          source: pull

  - name: pulling frontend images
    hosts: front
    tasks:
      - name: rest
        docker_image:
          name: registry-git.digikala.com/bi/rhodry/rest
          state: present
          source: pull
      - name: schema-registry
        docker_image:
          name: registry-git.digikala.com/bi/rhodry/schema-registry
          state: present
          source: pull
      - name: topics-ui
        docker_image:
          name: registry-git.digikala.com/bi/rhodry/landoop/topics-ui
          state: present
          source: pull
      - name: schema-registry-ui
        docker_image:
          name: registry-git.digikala.com/bi/rhodry/landoop/schema-registry-ui
          state: present
          source: pull
      - name: cadvisor
        docker_image:
          name: registry-git.digikala.com/bi/nevyn/cadvisor:0.44.0
          state: present
          source: pull
      - name: dglab
        docker_image:
          name: registry-git.digikala.com/bi/dgpy/dglab
          state: present
          source: pull
