---
  - name: setting up worker storage
    hosts: workers_ramezani
    become: true
    tasks:
      - name: adding sdb to ubuntu-vg
        lvg:
          vg: ubuntu-vg
          pvs: /dev/sda3,/dev/sdb
      - name: creating a new logical volume for data
        lvol:
          vg: ubuntu-vg
          lv: data
          size: +100%FREE
          shrink: no
          state: present
      - name: formatting the data filesystem
        filesystem:
          dev: /dev/mapper/ubuntu--vg-data
          state: present
          fstype: ext4
      - name: creating a data directory at root
        file:
          path: /data
          state: directory
          mode: '777'
      - name: creating a kafka data directory
        file:
          path: /data/kafka
          state: directory
          mode: '777'
      - name: creating a zookeeper data directory
        file:
          path: /data/zookeeper/data
          state: directory
          mode: '777'
      - name: creating a zookeeper log directory
        file:
          path: /data/zookeeper/datalog
          state: directory
          mode: '777'
      - name: mounting the data volume onto /data
        mount:
          path: /data
          src: /dev/mapper/ubuntu--vg-data
          state: mounted
          fstype: ext4
