{
 "title": "Rhodry",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center;\">\n<img src=\"https://biapps.digikala.com/images/rhodry-white-256.png\" />\n</div>"
   }
  },
  {
   "title": "Brokers",
   "type": "stat",
   "description": "Rhodry's running Kafka brokers",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rhodry_brokers", "legendFormat": "{{env}}" },
    {
     "expr": "count(kafka_controller_kafkacontroller_activebrokercount{job=\"rhodrylab2-jmx\"})",
     "legendFormat": "Lab2"
    }
   ]
  },
  {
   "title": "Running Connectors",
   "type": "stat",
   "description": "Rhodry Connect running connectors",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(env) (rhodry_connect_connector)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count (count by(connector) (kafka_connect_connector_task_status{status='running'}))",
     "legendFormat": "Lab2"
    }
   ]
  },
  {
   "title": "Change per Second",
   "type": "stat",
   "description": "Rhodry Consumption Rate",
   "gridPos": { "h": 4, "w": 7, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pipeline) (increase(rhodry_sink_row_count{env=\"production\"}[60s])) / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Rate",
   "type": "stat",
   "description": "Rhodry Consumption Rate",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=~\"rhodry-0[1-9]:9100|rhodry-1[0-8]:9100|\",device=~\"eth0\"}[1m] offset 5m))",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "Broker Storage (Production)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"rhodry-0[1-9]:9100|rhodry-1[0-8]:9100|\",mountpoint=\"/data\"} - node_filesystem_free_bytes{instance=~\"rhodry-0[1-9]:9100|rhodry-1[0-8]:9100|\",mountpoint=\"/data\"} ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Broker Storage (Lab2)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"rhodrylab2-0[1-5]:9100\"} - node_filesystem_free_bytes{instance=~\"rhodrylab2-0[1-5]:9100\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Broker Storage (Lab)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"rhodry-0[1-5]:9100\",mountpoint=\"/data\"} - node_filesystem_free_bytes{instance=~\"rhodry-0[1-5]:9100\",mountpoint=\"/data\"} ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consumption Rate per Database (Change-Tracking)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(name) (rate(rhodry_sink_row_count{pipeline=\"ct\", env=\"production\"}[1m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Consumption Rate per Database (CDC)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(name) (increase(rhodry_sink_row_count{pipeline=\"cdc\", env=\"production\"}[1m])) / 60",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}