
groups:
  - name: Prometheus
    rules:
    - alert: PrometheusTargetMissing
      expr: up == 0
      for: 5s
      labels:
        severity: critical
      annotations:
        summary: Prometheus target missing (instance {{ $labels.instance }})
        description: "A Prometheus target has disappeared. An exporter might be crashed.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
