{
 "title": "airflow monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "# Running Containers by nodes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 17, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "count by(instance) (increase(container_last_seen{job=\"cadvisor\", name!=\"\", instance=~\"bianalytics-01:8080|bianalytics-02:8080|bianalytics-03:8080\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "# Cpu Cores",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 17, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by(instance) (count by(instance, cpu) (node_cpu_seconds_total{instance=~\"(bianalytics-01:9100|bianalytics-02:9100|bianalytics-03:9100)\", mode='system'}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "# Total Memory",
     "type": "stat",
     "gridPos": { "h": 7, "w": 2, "x": 22, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "floor(node_memory_MemTotal_bytes{instance=~\"(bianalytics-01:9100|bianalytics-02:9100|bianalytics-03:9100)\"}/1e+9)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "% Cpu usage by nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{instance=~\"(bianalytics-01:9100|bianalytics-02:9100|bianalytics-03:9100)\",mode=\"idle\"}[5m])) * 100)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "% Memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 9, "y": 32 },
     "targets": [
      {
       "expr": "(sum by(instance) (node_memory_MemTotal_bytes) - sum by(instance) (node_memory_MemFree_bytes{instance=~\"(bianalytics-01:9100|bianalytics-02:9100|bianalytics-03:9100)\"} +node_memory_Buffers_bytes{instance=~\"(bianalytics-01:9100|bianalytics-02:9100|bianalytics-03:9100)\"} + node_memory_Cached_bytes{instance=~\"(bianalytics-01:9100|bianalytics-02:9100|bianalytics-03:9100)\"})) / sum by(instance) (node_memory_MemTotal_bytes) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Filesystem usage",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by(instance) ( node_filesystem_avail_bytes {mountpoint=\"/\", instance=~\"(bianalytics-01:9100|bianalytics-02:9100|bianalytics-03:9100)\"} / node_filesystem_size_bytes{mountpoint=\"/\", instance=~\"(bianalytics-01:9100|bianalytics-02:9100|bianalytics-03:9100)\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Dag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Scheduler heartbeat",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(airflow_agg_scheduler_heartbeat[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Dags",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airflow_agg_dagbag_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Dagbag import errors",
   "type": "stat",
   "description": "Number of errors from trying to parse DAG files",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "airflow_agg_dag_processing_import_errors"
    }
   ]
  },
  {
   "title": "Total successful tasks",
   "type": "stat",
   "description": "Overall task instances successes",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airflow_agg_ti_successes" }
   ]
  },
  {
   "title": "Total failed tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airflow_agg_ti_failures", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Celery Workers up",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "flower_worker_online", "legendFormat": "{{worker}}" }
   ]
  },
  {
   "title": "dag duration (minute)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "ceil(airflow_agg_dagrun_duration_success{quantile=\"0.5\"} / 60)",
     "legendFormat": "{{dag_id}}"
    }
   ]
  },
  {
   "title": "# Failed",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_agg_dagrun_duration_failed_count",
     "legendFormat": "{{dag_id}}"
    }
   ]
  },
  {
   "title": "# Success count",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_agg_dagrun_duration_success_count",
     "legendFormat": "{{dag_id}}"
    }
   ]
  },
  {
   "title": "Dag duration avg (minute)",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round((airflow_agg_dagrun_duration_success_sum / airflow_agg_dagrun_duration_success_count) / 60)",
     "legendFormat": "{{dag_id}}"
    }
   ]
  }
 ]
}