{
 "title": "BiApi",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center;\">\n<img src=\"https://biapps.digikala.com/images/biapi-256.png\" />\n</div>"
   }
  },
  {
   "title": "API Usage Breakdown",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (slug) (increase(biapi_usage[24h]))",
     "legendFormat": "{{slug}}"
    }
   ]
  },
  {
   "title": "# Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (increase(biapi_usage[1m])) / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status Codes Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (status) (increase(biapi_usage[5m]))",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}