{
 "title": "Kafka Connect",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "kubernetes_namespace",
    "label": "Namespace",
    "query": "query_result(kafka_connect_worker_connector_count{strimzi_io_kind=~\"KafkaConnect.*\"})"
   },
   {
    "name": "strimzi_connect_cluster_name",
    "label": "Cluster Name",
    "query": "query_result(kafka_connect_worker_connector_count{namespace=\"$kubernetes_namespace\", strimzi_io_kind=~\"KafkaConnect.*\"})"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values({job=~\"rhodrylab-jmx|rhodry-jmx|rhodrylab2-jmx\"},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of Connectors",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_count_count{job=\"${cluster}\"})"
    }
   ]
  },
  {
   "title": "Number of Tasks",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_task_count_count{job=\"${cluster}\"})"
    }
   ]
  },
  {
   "title": "Connection Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_connection_count_metric{job=\"${cluster}\"})",
     "legendFormat": "#consumer connections"
    },
    {
     "expr": "sum(kafka_producer_connection_count_metric{job=\"${cluster}\"})",
     "legendFormat": "#producer connections"
    },
    {
     "expr": "sum(kafka_admin_client_connection_count_metric{job=\"${cluster}\"})",
     "legendFormat": "#admin connections"
    }
   ]
  },
  {
   "title": "(Source/Producers) Outgoing Bytes per Second",
   "type": "timeseries",
   "description": "Bytes per second outgoing to Kafka from Connect worker. Includes data to internal topics.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_producer_outgoing_byte_total_metric{job=\"${cluster}\"}[5m])) by (job)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "(Sink/Consumers) Incoming Bytes per Second",
   "type": "timeseries",
   "description": "Bytes per second incoming to Kafka Connect worker from Kafka. Includes data from internal topics.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_consumer_incoming_byte_total_metric{job=\"${cluster}\"}[5m])) by (job)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "(Source/Producers) Record per Second",
   "type": "timeseries",
   "description": "Bytes per second outgoing to Kafka from Connect worker. Includes data to internal topics.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_producer_topic_record_send_total_metric{job=\"${cluster}\", clientid!~\"connect-.*\"}[5m])) by ()",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "(Source/Producers) Outgoing Bytes per Second",
   "type": "timeseries",
   "description": "Bytes per second outgoing to Kafka from Connect worker. Includes data to internal topics.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_consumer_fetch_manager_bytes_consumed_total_metric{job=\"${cluster}\", clientid!~\"connect-.*\"}[5m])) by (job)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Workers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Assigned Connectors by Worker",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_coordinator_assigned_connectors_metric{job=\"${cluster}\"}) by (job)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Rebalancing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_rebalance_rebalancing_metric{job=\"${cluster}\"})"
    }
   ]
  },
  {
   "title": "Assigned Tasks per Worker",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_coordinator_assigned_tasks_metric{job=\"${cluster}\"}) by (job)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Connectors and Tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connector Tasks with Issues",
   "type": "table",
   "description": "Connectors that have one or more tasks that are not in a running state, i.e. the state is one of paused, failed, unassigned or destroyed.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_paused_task_count{job=\"${cluster}\"}) by (connector) != 0"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_failed_task_count{job=\"${cluster}\"}) by (connector) != 0"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_unassigned_task_count{job=\"${cluster}\"}) by (connector) != 0"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_destroyed_task_count{job=\"${cluster}\"}) by (connector) != 0"
    }
   ]
  },
  {
   "title": "Connector Task State",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_running_task_count{job=\"${cluster}\"})",
     "legendFormat": "running"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_paused_task_count{job=\"${cluster}\"})",
     "legendFormat": "paused"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_failed_task_count{job=\"${cluster}\"})",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_unassigned_task_count{job=\"${cluster}\"})",
     "legendFormat": "unassigned"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_destroyed_task_count{job=\"${cluster}\"})",
     "legendFormat": "destroyed"
    }
   ]
  },
  {
   "title": "Connector Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(kafka_connect_connector_status{job=\"${cluster}\"} * on(connector) group_left(connector_class) kafka_connect_connector_connector_class{} * on (connector) group_left(connector_version) kafka_connect_connector_connector_version{} * on (connector) group_left(connector_type) kafka_connect_connector_connector_type{}) by (connector, status, connector_class, kubernetes_pod_name, connector_version, connector_type)"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=\"${cluster}\"}[5m])) by ()",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (jvm_memory_used_bytes{job=\"${cluster}\"}) by ()",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Time Spent in GC",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_sum{job=\"${cluster}\"}[5m])) by (job) * 10000",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "JVM Thread Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(jvm_threads_current{job=\"${cluster}\"}) by (job)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}