version: '3.7'

x-common: &common
  networks:
    - rhodry
  deploy:
    replicas: 1
    placement:
      constraints:
        - node.hostname == rhodrylab-01

services:
  mysql:
    <<: *common
    image: registry-git.digikala.com/bi/biservices/mysql
    command: [
      "--max-binlog-size", "4096"
    ]
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306

  mysql-cli:
    <<: *common
    image: registry-git.digikala.com/bi/biservices/mysql
    tty: true
    stdin_open: true
    command: [
      "mysql",
      "--host", "mysql",
      "--user", "root",
      "--password=${PASSWORD}"
    ]

  mssql:
    <<: *common
    image: registry-git.digikala.com/bi/biservices/mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${PASSWORD}
    ports:
      - ${SQL_SERVER_PORT}:1433

  mssql-cli:
    <<: *common
    image: registry-git.digikala.com/bi/biservices/mssql
    tty: true
    stdin_open: true
    command: [
      "/opt/mssql-tools/bin/sqlcmd",
      "-S", "mssql",
      "-U", "sa",
      "-P", "${PASSWORD}"
    ]

networks:
  rhodry:
    external: true
