version: '3.7'

services:
  exporter-sales:
    image: ${CI_REGISTRY_IMAGE}/exporters/sales
    ports:
      - ${PORT}:80
    environment:
      KSQL_HOST: ${KSQL_HOST}
    secrets:
      - source: DG_BIWAREHOUSING_USER_BIAPPS
        target: DG_BIWAREHOUSING_USER
      - source: DG_BIWAREHOUSING_PASS_BIAPPS_2
        target: DG_BIWAREHOUSING_PASS

secrets:
  DG_BIWAREHOUSING_USER_BIAPPS:
    external: true
  DG_BIWAREHOUSING_PASS_BIAPPS_2:
    external: true
