version: '3.7'

x-network: &network
  networks:
    - rhodry

x-deploy-on-front: &deploy-on-front
  deploy:
    replicas: 1
    placement:
      constraints: [node.labels.rhodry==front]

x-deploy-replicated: &deploy-replicated
  deploy:
    replicas: 18
    placement:
      constraints: [node.labels.rhodry==worker]
      # max_replicas_per_node: 1

x-zookeeper-envs: &zookeeper-envs
  ZOO_TICK_TIME: 2000
  ZOO_SERVERS: server.1=zookeeper-01:12888:13888;12181 server.2=zookeeper-02:22888:23888;22181 server.3=zookeeper-03:32888:33888;32181

x-kafka-envs: &kafka-envs
  KAFKA_ZOOKEEPER_CONNECT: zookeeper-01:12181,zookeeper-02:22181,zookeeper-03:32181/kafka
  # KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
  KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
  KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 3
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
  KAFKA_JMX_PORT: 9101
  KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
  # CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka-01:29091,kafka-02:29092,kafka-03:29093,kafka-04:29094,kafka-05:29095,kafka-06:29096,kafka-07:29097,kafka-08:29098,kafka-09:29099,kafka-10:29190,kafka-11:29191,kafka-12:29192,kafka-13:29193,kafka-14:29194,kafka-15:29195,kafka-16:29196,kafka-17:29197,kafka-18:29198
  # CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
  # CONFLUENT_METRICS_ENABLE: 'true'
  CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
  KAFKA_FETCH_MAX_BYTES: ${MAXIMUM_BYTES_ALLOWED_PER_MESSAGE}
  KAFKA_REPLICA_FETCH_MAX_BYTES: ${MAXIMUM_BYTES_ALLOWED_PER_MESSAGE}
  KAFKA_MESSAGE_MAX_BYTES: ${MAXIMUM_BYTES_ALLOWED_PER_MESSAGE}
  KAFKA_REPLICA_FETCH_RESPONSE_MAX_BYTES: ${MAXIMUM_BYTES_ALLOWED_PER_MESSAGE}
  
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_INT:PLAINTEXT,PLAINTEXT_EXT:PLAINTEXT,SASL_EXT:SASL_PLAINTEXT,SASL_INT:SASL_PLAINTEXT
  KAFKA_INTER_BROKER_LISTENER_NAME: SASL_INT
  KAFKA_OPTS:
    -Djava.security.auth.login.config=/run/secrets/KAFKA_JAAS
  KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
  KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
  ZOOKEEPER_SASL_ENABLED: "false"
  KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
  KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
  KAFKA_SUPER_USERS: "User:admin"
  KAFKA_CONFLUENT_REPORTERS_TELEMETRY_AUTO_ENABLE: "false"

x-zookeeper-common: &zookeeper-common
  image: ${CI_REGISTRY_IMAGE}/zookeeper
  <<: *network
  volumes:
    - /data/zookeeper/data:/data
    - /data/zookeeper/datalog:/datalog

x-kafka-common: &kafka-common
  image: ${CI_REGISTRY_IMAGE}/kafka:${KAKFA_BROKER_VERSION}
  <<: *network
  secrets:
    - source: KAFKA_JAAS_2024-08-18
      target: KAFKA_JAAS
  volumes:
    - /data/kafka:/var/lib/kafka/data

x-connect-common: &connect-common
  image: ${CI_REGISTRY_IMAGE}/connect:${CONNECT_VERSION}
  <<: *network

x-connect-envs: &connect-envs
  CONNECT_GROUP_ID: connect
  CONNECT_CONFIG_STORAGE_TOPIC: connect-configs
  CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets
  CONNECT_STATUS_STORAGE_TOPIC: connect-statuses
  CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 3
  CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 3
  CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 3
  CONNECT_BOOTSTRAP_SERVERS: ${BOOTSTRAP_SERVERS}
  CONNECT_KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
  CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
  CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
  CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
  CONNECT_LISTENERS: http://0.0.0.0:8083
  CONNECT_REST_PORT: 8083
  KAFKA_HEAP_OPTS: '-Xmx12G -Xms12G'

services:
  zookeeper-01:
    <<: *zookeeper-common
    hostname: zookeeper-01
    ports:
      - 12181:2181
      - 12888:2888
      - 13888:3888
    deploy:
      placement:
        constraints:
          - node.hostname == rhodry-01
    environment:
      <<: *zookeeper-envs
      ZOO_MY_ID: 1

  zookeeper-02:
    <<: *zookeeper-common
    hostname: zookeeper-02
    ports:
      - 22181:2181
      - 22888:2888
      - 23888:3888
    deploy:
      placement:
        constraints:
          - node.hostname == rhodry-02
    environment:
      <<: *zookeeper-envs
      ZOO_MY_ID: 2

  zookeeper-03:
    <<: *zookeeper-common
    hostname: zookeeper-03
    ports:
      - 32181:2181
      - 32888:2888
      - 33888:3888
    deploy:
      placement:
        constraints:
          - node.hostname == rhodry-03
    environment:
      <<: *zookeeper-envs
      ZOO_MY_ID: 3

  kafka-01:
    <<: *kafka-common
    deploy:
      placement:
        constraints:
          - node.hostname == rhodry-01
    ports:
      - 29091:29091 # Unauthenticated | Internal | For Connect, Schema registry, etc.
      - 28091:28091 # Authenticated | Interal | For broker-broker comms.
      - 27091:27091 # Unauthenticated | External | For BI clients only.
      - 26091:26091 # Authenticated | External | For the rest of the organization.
    environment:
      <<: *kafka-envs
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT_INT://0.0.0.0:29091,SASL_INT://0.0.0.0:28091,PLAINTEXT_EXT://0.0.0.0:27091,SASL_EXT://0.0.0.0:26091
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INT://kafka-01:29091,SASL_INT://kafka-01:28091,PLAINTEXT_EXT://172.17.23.164:27091,SASL_EXT://172.17.23.164:26091

  kafka-02:
    <<: *kafka-common
    deploy:
      placement:
        constraints:
          - node.hostname == rhodry-02
    ports:
      - 29092:29092 # Unauthenticated | Internal | For Connect, Schema registry, etc.
      - 28092:28092 # Authenticated | Interal | For broker-broker comms.
      - 27092:27092 # Unauthenticated | External | For BI clients only.
      - 26092:26092 # Authenticated | External | For the rest of the organization.
    environment:
      <<: *kafka-envs
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: PLAINTEXT_INT://0.0.0.0:29092,SASL_INT://0.0.0.0:28092,PLAINTEXT_EXT://0.0.0.0:27092,SASL_EXT://0.0.0.0:26092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INT://kafka-02:29092,SASL_INT://kafka-02:28092,PLAINTEXT_EXT://172.17.23.165:27092,SASL_EXT://172.17.23.165:26092

  kafka-03:
    <<: *kafka-common
    deploy:
      placement:
        constraints:
          - node.hostname == rhodry-03
    ports:
      - 29093:29093 # Unauthenticated | Internal | For Connect, Schema registry, etc.
      - 28093:28093 # Authenticated | Interal | For broker-broker comms.
      - 27093:27093 # Unauthenticated | External | For BI clients only.
      - 26093:26093 # Authenticated | External | For the rest of the organization.
    environment:
      <<: *kafka-envs
      KAFKA_BROKER_ID: 3
      KAFKA_LISTENERS: PLAINTEXT_INT://0.0.0.0:29093,SASL_INT://0.0.0.0:28093,PLAINTEXT_EXT://0.0.0.0:27093,SASL_EXT://0.0.0.0:26093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INT://kafka-03:29093,SASL_INT://kafka-03:28093,PLAINTEXT_EXT://172.17.23.166:27093,SASL_EXT://172.17.23.166:26093

  kafka-04:
    <<: *kafka-common
    deploy:
      placement:
        constraints:
          - node.hostname == rhodry-04
    ports:
      - 29094:29094 # Unauthenticated | Internal | For Connect, Schema registry, etc.
      - 28094:28094 # Authenticated | Interal | For broker-broker comms.
      - 27094:27094 # Unauthenticated | External | For BI clients only.
      - 26094:26094 # Authenticated | External | For the rest of the organization.
    environment:
      <<: *kafka-envs
      KAFKA_BROKER_ID: 4
      KAFKA_LISTENERS: PLAINTEXT_INT://0.0.0.0:29094,SASL_INT://0.0.0.0:28094,PLAINTEXT_EXT://0.0.0.0:27094,SASL_EXT://0.0.0.0:26094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INT://kafka-04:29094,SASL_INT://kafka-04:28094,PLAINTEXT_EXT://172.17.23.167:27094,SASL_EXT://172.17.23.167:26094

  kafka-05:
    <<: *kafka-common
    deploy:
      placement:
        constraints:
          - node.hostname == rhodry-05
    ports:
      - 29095:29095 # Unauthenticated | Internal | For Connect, Schema registry, etc.
      - 28095:28095 # Authenticated | Interal | For broker-broker comms.
      - 27095:27095 # Unauthenticated | External | For BI clients only.
      - 26095:26095 # Authenticated | External | For the rest of the organization.
    environment:
      <<: *kafka-envs
      KAFKA_BROKER_ID: 5
      KAFKA_LISTENERS: PLAINTEXT_INT://0.0.0.0:29095,SASL_INT://0.0.0.0:28095,PLAINTEXT_EXT://0.0.0.0:27095,SASL_EXT://0.0.0.0:26095
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INT://kafka-05:29095,SASL_INT://kafka-05:28095,PLAINTEXT_EXT://172.17.23.168:27095,SASL_EXT://172.17.23.168:26095

  kafka-06:
    <<: *kafka-common
    deploy:
      placement:
        constraints:
          - node.hostname == rhodry-06
    ports:
      - 29096:29096 # Unauthenticated | Internal | For Connect, Schema registry, etc.
      - 28096:28096 # Authenticated | Interal | For broker-broker comms.
      - 27096:27096 # Unauthenticated | External | For BI clients only.
      - 26096:26096 # Authenticated | External | For the rest of the organization.
    environment:
      <<: *kafka-envs
      KAFKA_BROKER_ID: 6
      KAFKA_LISTENERS: PLAINTEXT_INT://0.0.0.0:29096,SASL_INT://0.0.0.0:28096,PLAINTEXT_EXT://0.0.0.0:27096,SASL_EXT://0.0.0.0:26096
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INT://kafka-06:29096,SASL_INT://kafka-06:28096,PLAINTEXT_EXT://172.17.23.169:27096,SASL_EXT://172.17.23.169:26096

  kafka-07:
    <<: *kafka-common
    deploy:
      placement:
        constraints:
          - node.hostname == rhodry-07
    ports:
      - 29097:29097 # Unauthenticated | Internal | For Connect, Schema registry, etc.
      - 28097:28097 # Authenticated | Interal | For broker-broker comms.
      - 27097:27097 # Unauthenticated | External | For BI clients only.
      - 26097:26097 # Authenticated | External | For the rest of the organization.
    environment:
      <<: *kafka-envs
      KAFKA_BROKER_ID: 7
      KAFKA_LISTENERS: PLAINTEXT_INT://0.0.0.0:29097,SASL_INT://0.0.0.0:28097,PLAINTEXT_EXT://0.0.0.0:27097,SASL_EXT://0.0.0.0:26097
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INT://kafka-07:29097,SASL_INT://kafka-07:28097,PLAINTEXT_EXT://172.17.23.170:27097,SASL_EXT://172.17.23.170:26097

  kafka-08:
    <<: *kafka-common
    deploy:
      placement:
        constraints:
          - node.hostname == rhodry-08
    ports:
      - 29098:29098 # Unauthenticated | Internal | For Connect, Schema registry, etc.
      - 28098:28098 # Authenticated | Interal | For broker-broker comms.
      - 27098:27098 # Unauthenticated | External | For BI clients only.
      - 26098:26098 # Authenticated | External | For the rest of the organization.
    environment:
      <<: *kafka-envs
      KAFKA_BROKER_ID: 8
      KAFKA_LISTENERS: PLAINTEXT_INT://0.0.0.0:29098,SASL_INT://0.0.0.0:28098,PLAINTEXT_EXT://0.0.0.0:27098,SASL_EXT://0.0.0.0:26098
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INT://kafka-08:29098,SASL_INT://kafka-08:28098,PLAINTEXT_EXT://172.17.23.171:27098,SASL_EXT://172.17.23.171:26098

  kafka-09:
    <<: *kafka-common
    deploy:
      placement:
        constraints:
          - node.hostname == rhodry-09
    ports:
      - 29099:29099 # Unauthenticated | Internal | For Connect, Schema registry, etc.
      - 28099:28099 # Authenticated | Interal | For broker-broker comms.
      - 27099:27099 # Unauthenticated | External | For BI clients only.
      - 26099:26099 # Authenticated | External | For the rest of the organization.
    environment:
      <<: *kafka-envs
      KAFKA_BROKER_ID: 9
      KAFKA_LISTENERS: PLAINTEXT_INT://0.0.0.0:29099,SASL_INT://0.0.0.0:28099,PLAINTEXT_EXT://0.0.0.0:27099,SASL_EXT://0.0.0.0:26099
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INT://kafka-09:29099,SASL_INT://kafka-09:28099,PLAINTEXT_EXT://172.17.23.172:27099,SASL_EXT://172.17.23.172:26099

  kafka-10:
    <<: *kafka-common
    deploy:
      placement:
        constraints:
          - node.hostname == rhodry-10
    ports:
      - 29190:29190 # Unauthenticated | Internal | For Connect, Schema registry, etc.
      - 28190:28190 # Authenticated | Interal | For broker-broker comms.
      - 27190:27190 # Unauthenticated | External | For BI clients only.
      - 26190:26190 # Authenticated | External | For the rest of the organization.
    environment:
      <<: *kafka-envs
      KAFKA_BROKER_ID: 10
      KAFKA_LISTENERS: PLAINTEXT_INT://0.0.0.0:29190,SASL_INT://0.0.0.0:28190,PLAINTEXT_EXT://0.0.0.0:27190,SASL_EXT://0.0.0.0:26190
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INT://kafka-10:29190,SASL_INT://kafka-10:28190,PLAINTEXT_EXT://172.17.23.173:27190,SASL_EXT://172.17.23.173:26190

  kafka-11:
    <<: *kafka-common
    deploy:
      placement:
        constraints:
          - node.hostname == rhodry-11
    ports:
      - 29191:29191 # Unauthenticated | Internal | For Connect, Schema registry, etc.
      - 28191:28191 # Authenticated | Interal | For broker-broker comms.
      - 27191:27191 # Unauthenticated | External | For BI clients only.
      - 26191:26191 # Authenticated | External | For the rest of the organization.
    environment:
      <<: *kafka-envs
      KAFKA_BROKER_ID: 11
      KAFKA_LISTENERS: PLAINTEXT_INT://0.0.0.0:29191,SASL_INT://0.0.0.0:28191,PLAINTEXT_EXT://0.0.0.0:27191,SASL_EXT://0.0.0.0:26191
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INT://kafka-11:29191,SASL_INT://kafka-11:28191,PLAINTEXT_EXT://172.17.23.174:27191,SASL_EXT://172.17.23.174:26191

  kafka-12:
    <<: *kafka-common
    deploy:
      placement:
        constraints:
          - node.hostname == rhodry-12
    ports:
      - 29192:29192 # Unauthenticated | Internal | For Connect, Schema registry, etc.
      - 28192:28192 # Authenticated | Interal | For broker-broker comms.
      - 27192:27192 # Unauthenticated | External | For BI clients only.
      - 26192:26192 # Authenticated | External | For the rest of the organization.
    environment:
      <<: *kafka-envs
      KAFKA_BROKER_ID: 12
      KAFKA_LISTENERS: PLAINTEXT_INT://0.0.0.0:29192,SASL_INT://0.0.0.0:28192,PLAINTEXT_EXT://0.0.0.0:27192,SASL_EXT://0.0.0.0:26192
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INT://kafka-12:29192,SASL_INT://kafka-12:28192,PLAINTEXT_EXT://172.17.23.175:27192,SASL_EXT://172.17.23.175:26192

  kafka-13:
    <<: *kafka-common
    deploy:
      placement:
        constraints:
          - node.hostname == rhodry-13
    ports:
      - 29193:29193 # Unauthenticated | Internal | For Connect, Schema registry, etc.
      - 28193:28193 # Authenticated | Interal | For broker-broker comms.
      - 27193:27193 # Unauthenticated | External | For BI clients only.
      - 26193:26193 # Authenticated | External | For the rest of the organization.
    environment:
      <<: *kafka-envs
      KAFKA_BROKER_ID: 13
      KAFKA_LISTENERS: PLAINTEXT_INT://0.0.0.0:29193,SASL_INT://0.0.0.0:28193,PLAINTEXT_EXT://0.0.0.0:27193,SASL_EXT://0.0.0.0:26193
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INT://kafka-13:29193,SASL_INT://kafka-13:28193,PLAINTEXT_EXT://172.17.23.176:27193,SASL_EXT://172.17.23.176:26193

  kafka-14:
    <<: *kafka-common
    deploy:
      placement:
        constraints:
          - node.hostname == rhodry-14
    ports:
      - 29194:29194 # Unauthenticated | Internal | For Connect, Schema registry, etc.
      - 28194:28194 # Authenticated | Interal | For broker-broker comms.
      - 27194:27194 # Unauthenticated | External | For BI clients only.
      - 26194:26194 # Authenticated | External | For the rest of the organization.
    environment:
      <<: *kafka-envs
      KAFKA_BROKER_ID: 14
      KAFKA_LISTENERS: PLAINTEXT_INT://0.0.0.0:29194,SASL_INT://0.0.0.0:28194,PLAINTEXT_EXT://0.0.0.0:27194,SASL_EXT://0.0.0.0:26194
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INT://kafka-14:29194,SASL_INT://kafka-14:28194,PLAINTEXT_EXT://172.17.23.177:27194,SASL_EXT://172.17.23.177:26194

  kafka-15:
    <<: *kafka-common
    deploy:
      placement:
        constraints:
          - node.hostname == rhodry-15
    ports:
      - 29195:29195 # Unauthenticated | Internal | For Connect, Schema registry, etc.
      - 28195:28195 # Authenticated | Interal | For broker-broker comms.
      - 27195:27195 # Unauthenticated | External | For BI clients only.
      - 26195:26195 # Authenticated | External | For the rest of the organization.
    environment:
      <<: *kafka-envs
      KAFKA_BROKER_ID: 15
      KAFKA_LISTENERS: PLAINTEXT_INT://0.0.0.0:29195,SASL_INT://0.0.0.0:28195,PLAINTEXT_EXT://0.0.0.0:27195,SASL_EXT://0.0.0.0:26195
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INT://kafka-15:29195,SASL_INT://kafka-15:28195,PLAINTEXT_EXT://172.17.23.178:27195,SASL_EXT://172.17.23.178:26195

  kafka-16:
    <<: *kafka-common
    deploy:
      placement:
        constraints:
          - node.hostname == rhodry-16
    ports:
      - 29196:29196 # Unauthenticated | Internal | For Connect, Schema registry, etc.
      - 28196:28196 # Authenticated | Interal | For broker-broker comms.
      - 27196:27196 # Unauthenticated | External | For BI clients only.
      - 26196:26196 # Authenticated | External | For the rest of the organization.
    environment:
      <<: *kafka-envs
      KAFKA_BROKER_ID: 16
      KAFKA_LISTENERS: PLAINTEXT_INT://0.0.0.0:29196,SASL_INT://0.0.0.0:28196,PLAINTEXT_EXT://0.0.0.0:27196,SASL_EXT://0.0.0.0:26196
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INT://kafka-16:29196,SASL_INT://kafka-16:28196,PLAINTEXT_EXT://172.17.23.179:27196,SASL_EXT://172.17.23.179:26196

  kafka-17:
    <<: *kafka-common
    deploy:
      placement:
        constraints:
          - node.hostname == rhodry-17
    ports:
      - 29197:29197 # Unauthenticated | Internal | For Connect, Schema registry, etc.
      - 28197:28197 # Authenticated | Interal | For broker-broker comms.
      - 27197:27197 # Unauthenticated | External | For BI clients only.
      - 26197:26197 # Authenticated | External | For the rest of the organization.
    environment:
      <<: *kafka-envs
      KAFKA_BROKER_ID: 17
      KAFKA_LISTENERS: PLAINTEXT_INT://0.0.0.0:29197,SASL_INT://0.0.0.0:28197,PLAINTEXT_EXT://0.0.0.0:27197,SASL_EXT://0.0.0.0:26197
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INT://kafka-17:29197,SASL_INT://kafka-17:28197,PLAINTEXT_EXT://172.17.23.180:27197,SASL_EXT://172.17.23.180:26197

  kafka-18:
    <<: *kafka-common
    deploy:
      placement:
        constraints:
          - node.hostname == rhodry-18
    ports:
      - 29198:29198 # Unauthenticated | Internal | For Connect, Schema registry, etc.
      - 28198:28198 # Authenticated | Interal | For broker-broker comms.
      - 27198:27198 # Unauthenticated | External | For BI clients only.
      - 26198:26198 # Authenticated | External | For the rest of the organization.
    environment:
      <<: *kafka-envs
      KAFKA_BROKER_ID: 18
      KAFKA_LISTENERS: PLAINTEXT_INT://0.0.0.0:29198,SASL_INT://0.0.0.0:28198,PLAINTEXT_EXT://0.0.0.0:27198,SASL_EXT://0.0.0.0:26198
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INT://kafka-18:29198,SASL_INT://kafka-18:28198,PLAINTEXT_EXT://172.17.23.181:27198,SASL_EXT://172.17.23.181:26198

  # connect:
  #   image: ${CI_REGISTRY_IMAGE}/connect
  #   hostname: connect
  #   <<: *network
  #   <<: *deploy-replicated
  #   ports:
  #     - ${CONNECT_REST_PORT}:8083
  #   environment:
  #     GROUP_ID: connect
  #     CONFIG_STORAGE_TOPIC: connect-configs
  #     OFFSET_STORAGE_TOPIC: connect-offsets
  #     STATUS_STORAGE_TOPIC: connect-statuses
  #     CONFIG_STORAGE_REPLICATION_FACTOR: 3
  #     OFFSET_STORAGE_REPLICATION_FACTOR: 3
  #     STATUS_STORAGE_REPLICATION_FACTOR: 3
  #     BOOTSTRAP_SERVERS: kafka-01:29091,kafka-02:29092,kafka-03:29093,kafka-04:29094,kafka-05:29095,kafka-06:29096,kafka-07:29097,kafka-08:29098,kafka-09:29099,kafka-10:29190,kafka-11:29191,kafka-12:29192,kafka-13:29193,kafka-14:29194,kafka-15:29195,kafka-16:29196,kafka-17:29197,kafka-18:29198
  #     KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
  #     VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
  #     CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
  #     CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
  #     HEAP_OPTS: '-Xmx12G -Xms12G'

  connect-01:
    <<: *connect-common
    container_name: connect-01
    hostname: connect-01
    ports:
      - ${CONNECT_REST_PORT}:8083
    deploy:
      placement:
        constraints:
          - node.hostname == rhodry-01
    environment:
      <<: *connect-envs
      CONNECT_REST_ADVERTISED_HOST_NAME: connect-01

  connect-02:
    <<: *connect-common
    container_name: connect-02
    hostname: connect-02
    deploy:
      placement:
        constraints:
          - node.hostname == rhodry-02
    environment:
      <<: *connect-envs
      CONNECT_REST_ADVERTISED_HOST_NAME: connect-02

  connect-03:
    <<: *connect-common
    container_name: connect-03
    hostname: connect-03
    deploy:
      placement:
        constraints:
          - node.hostname == rhodry-03
    environment:
      <<: *connect-envs
      CONNECT_REST_ADVERTISED_HOST_NAME: connect-03

  connect-04:
    <<: *connect-common
    container_name: connect-04
    hostname: connect-04
    deploy:
      placement:
        constraints:
          - node.hostname == rhodry-04
    environment:
      <<: *connect-envs
      CONNECT_REST_ADVERTISED_HOST_NAME: connect-04

  connect-05:
    <<: *connect-common
    container_name: connect-05
    hostname: connect-05
    deploy:
      placement:
        constraints:
          - node.hostname == rhodry-05
    environment:
      <<: *connect-envs
      CONNECT_REST_ADVERTISED_HOST_NAME: connect-05

  connect-06:
    <<: *connect-common
    container_name: connect-06
    hostname: connect-06
    deploy:
      placement:
        constraints:
          - node.hostname == rhodry-06
    environment:
      <<: *connect-envs
      CONNECT_REST_ADVERTISED_HOST_NAME: connect-06

  connect-07:
    <<: *connect-common
    container_name: connect-07
    hostname: connect-07
    deploy:
      placement:
        constraints:
          - node.hostname == rhodry-07
    environment:
      <<: *connect-envs
      CONNECT_REST_ADVERTISED_HOST_NAME: connect-07

  connect-08:
    <<: *connect-common
    container_name: connect-08
    hostname: connect-08
    deploy:
      placement:
        constraints:
          - node.hostname == rhodry-08
    environment:
      <<: *connect-envs
      CONNECT_REST_ADVERTISED_HOST_NAME: connect-08

  connect-09:
    <<: *connect-common
    container_name: connect-09
    hostname: connect-09
    deploy:
      placement:
        constraints:
          - node.hostname == rhodry-09
    environment:
      <<: *connect-envs
      CONNECT_REST_ADVERTISED_HOST_NAME: connect-09

  connect-10:
    <<: *connect-common
    container_name: connect-10
    hostname: connect-10
    deploy:
      placement:
        constraints:
          - node.hostname == rhodry-10
    environment:
      <<: *connect-envs
      CONNECT_REST_ADVERTISED_HOST_NAME: connect-10

  connect-11:
    <<: *connect-common
    container_name: connect-11
    hostname: connect-11
    deploy:
      placement:
        constraints:
          - node.hostname == rhodry-11
    environment:
      <<: *connect-envs
      CONNECT_REST_ADVERTISED_HOST_NAME: connect-11

  connect-12:
    <<: *connect-common
    container_name: connect-12
    hostname: connect-12
    deploy:
      placement:
        constraints:
          - node.hostname == rhodry-12
    environment:
      <<: *connect-envs
      CONNECT_REST_ADVERTISED_HOST_NAME: connect-12

  connect-13:
    <<: *connect-common
    container_name: connect-13
    hostname: connect-13
    deploy:
      placement:
        constraints:
          - node.hostname == rhodry-13
    environment:
      <<: *connect-envs
      CONNECT_REST_ADVERTISED_HOST_NAME: connect-13

  connect-14:
    <<: *connect-common
    container_name: connect-14
    hostname: connect-14
    deploy:
      placement:
        constraints:
          - node.hostname == rhodry-14
    environment:
      <<: *connect-envs
      CONNECT_REST_ADVERTISED_HOST_NAME: connect-14

  connect-15:
    <<: *connect-common
    container_name: connect-15
    hostname: connect-15
    deploy:
      placement:
        constraints:
          - node.hostname == rhodry-15
    environment:
      <<: *connect-envs
      CONNECT_REST_ADVERTISED_HOST_NAME: connect-15

  connect-16:
    <<: *connect-common
    container_name: connect-16
    hostname: connect-16
    deploy:
      placement:
        constraints:
          - node.hostname == rhodry-16
    environment:
      <<: *connect-envs
      CONNECT_REST_ADVERTISED_HOST_NAME: connect-16

  connect-17:
    <<: *connect-common
    container_name: connect-17
    hostname: connect-17
    deploy:
      placement:
        constraints:
          - node.hostname == rhodry-17
    environment:
      <<: *connect-envs
      CONNECT_REST_ADVERTISED_HOST_NAME: connect-17

  connect-18:
    <<: *connect-common
    container_name: connect-18
    hostname: connect-18
    deploy:
      placement:
        constraints:
          - node.hostname == rhodry-18
    environment:
      <<: *connect-envs
      CONNECT_REST_ADVERTISED_HOST_NAME: connect-18

  schema-registry:
    image: ${CI_REGISTRY_IMAGE}/schema-registry
    <<: *network
    <<: *deploy-on-front
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: ${BOOTSTRAP_SERVERS}
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_SCHEMA_REGISTRY_INTER_INSTANCE_PROTOCOL: "http"

  rest-proxy:
    image: ${CI_REGISTRY_IMAGE}/rest
    <<: *network
    <<: *deploy-on-front
    ports:
      - ${KAFKA_REST_PORT}:8082
    environment:
      KAFKA_REST_HOST_NAME: rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: ${BOOTSTRAP_SERVERS}
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
      KAFKA_REST_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'

  topics-ui:
    image: ${CI_REGISTRY_IMAGE}/landoop/topics-ui
    <<: *network
    <<: *deploy-on-front
    environment:
      KAFKA_REST_PROXY_URL: http://rest-proxy:8082
      PROXY: "true"
    ports:
      - ${TOPICS_UI_PORT}:8000

  schema-registry-ui:
    image: ${CI_REGISTRY_IMAGE}/landoop/schema-registry-ui
    <<: *network
    <<: *deploy-on-front
    environment:
      SCHEMAREGISTRY_URL: http://schema-registry:8081
      PROXY: "true"
    ports:
      - ${SCHEMA_REGISTRY_UI_PORT}:8000
  
  connect-ui:
    image: ${CI_REGISTRY_IMAGE}/landoop/connect-ui
    <<: *network
    <<: *deploy-on-front
    environment:
      CONNECT_URL: http://connect-01:8083
      PROXY: "true"
    ports:
      - ${CONNECT_UI_PORT}:8000

  rhodry:
    image: ${CI_REGISTRY_IMAGE}:${RHODRY_VERSION}
    <<: *deploy-on-front
    <<: *network
    ports:
      - ${RHODRY_REST_PORT}:80
    environment:
      CLUSTER: ${CLUSTER}
      BILOG_DBS: ${BILOG_DBS}
      BILOG_SERVER: ${BILOG_SERVER}
      RHODRY_DB: ${RHODRY_DB}
      RHODRY_SERVER: ${RHODRY_SERVER}
      RABBIT_QUEUE_CREATE_TOPICS: ${RABBIT_QUEUE_CREATE_TOPICS}
      BI_RABBIT_HOST: ${RABBIT_HOST}
    secrets:
      - RHODRY_USER
      - RHODRY_PASS
      - SUPERNOVA_PASS
      - source: SUPERNOVA_SLAVE_USER
        target: SUPERNOVA_USER
      - source: RABBIT_PASS
        target: BI_RABBIT_PASS
      # - source: BILOG_USER
        # target: DG_BIWAREHOUSING_USER
      # - source: BILOG_PASS
        # target: DG_BIWAREHOUSING_PASS

  lab:
    image: registry-git.digikala.com/bi/dgpy/dglab
    <<: *deploy-on-front
    entrypoint: [ "jupyter", "lab", "--app_dir", "/home/dgpy", "--ip", "0.0.0.0", "--port", "8888" ]
    networks:
      - rhodry
    secrets:
      - BILOG_USER
      - BILOG_PASS
      - SUPERNOVA_MASTER_USER
      - SUPERNOVA_SLAVE_USER
      - SUPERNOVA_PASS
    ports:
      - ${LAB_PORT}:8888
    volumes:
      - dglab:/home/dgpy

  rhodry-topics-consumer:
    image: ${CI_REGISTRY_IMAGE}:${RHODRY_VERSION}
    <<: *deploy-on-front
    <<: *network
    entrypoint: [ "python3" ]
    command: [ "rhodry_topics_consumer.py" ]
    environment:
      CLUSTER: ${CLUSTER}
      RABBIT_HOST: ${RABBIT_HOST}
      RABBIT_USER: ${RABBIT_USER}
      RABBIT_QUEUE_CREATE_TOPICS: ${RABBIT_QUEUE_CREATE_TOPICS}
    secrets:
      - RABBIT_PASS

  rhodry-topics-alter-consumer:
    image: ${CI_REGISTRY_IMAGE}:${RHODRY_VERSION}
    <<: *deploy-on-front
    <<: *network
    entrypoint: [ "python3" ]
    command: [ "rhodry_topics_alter_consumer.py" ]
    environment:
      CLUSTER: ${CLUSTER}
      RABBIT_HOST: ${RABBIT_HOST}
      RABBIT_USER: ${RABBIT_USER}
      RABBIT_QUEUE_ALTER_TOPICS: ${RABBIT_QUEUE_ALTER_TOPICS}
    secrets:
      - RABBIT_PASS

  kafdrop:
    image: ${CI_REGISTRY_IMAGE}/kafdrop
    <<: *deploy-on-front
    <<: *network
    environment:
      KAFKA_BROKERCONNECT: ${BOOTSTRAP_SERVERS}
      SERVER_SERVLET_CONTEXTPATH: '/'
      JVM_OPTS: '-Xms1g -Xmx1g'
      SERVER_PORT: 9000
      MANAGEMENT_SERVER_PORT: 9000
      SCHEMAREGISTRY_CONNECT: 'http://schema-registry:8081'
    ports:
      - ${KAFDROP_PORT}:9000


  kafka-ui:
    image: ${CI_REGISTRY_IMAGE}/kafka-ui:${KAFKA_UI_VERSION}
    command: [
      "/bin/sh",
      "-c",
      "export SPRING_LDAP_ADMIN_PASSWORD=$$(cat /run/secrets/LDAP_ADMIN_PASSWORD) && java --add-opens java.rmi/javax.rmi.ssl=ALL-UNNAMED  $JAVA_OPTS -jar kafka-ui-api.jar"
    ]
    <<: *network
    <<: *deploy-on-front
    ports:
      - ${KAFKA_UI_PORT}:8080
      - 80:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"

      AUTH_TYPE: "LDAP"
      SPRING_LDAP_URLS: "ldap://BH-DC01.digikala.com:389"
      SPRING_LDAP_BASE: "DC=digikala,DC=COM" 
      SPRING_LDAP_ADMIN_USER: "CN=BI LDAP,OU=Digikala-ServiceAccount,OU=Digikala,OU=DKGroup,DC=digikala,DC=COM"
      SPRING_LDAP_USER_FILTER_SEARCH_BASE: "OU=Data & Insight,OU=Technology,OU=Digikala-Users,OU=Digikala,OU=DKGroup,DC=digikala,DC=COM"
      SPRING_LDAP_USER_FILTER_SEARCH_FILTER: (&(SAMAccountName={0})(objectClass=user)(memberof=CN=HQ-BIDevops,OU=DK-BI-Groups,OU=BI,OU=Enterprise Services,DC=digikala,DC=COM))
      SPRING_LDAP_GROUP_FILTER_SEARCH_BASE: DC=digikala,DC=COM 


      KAFKA_CLUSTERS_0_NAME: production
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: ${BOOTSTRAP_SERVERS}
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: production
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: "http://connect-01:8083"
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: "http://schema-registry:8081"
      #KAFKA_CLUSTERS_0_KSQLDBSERVER: "http://ksqldb-01:8088"

      KAFKA_CLUSTERS_1_NAME: lab
      KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS: ${BOOTSTRAP_SERVERS_LAB01}
      KAFKA_CLUSTERS_1_METRICS_PORT: 9997
      KAFKA_CLUSTERS_1_KAFKACONNECT_0_NAME: lab
      KAFKA_CLUSTERS_1_KAFKACONNECT_0_ADDRESS: "http://172.17.23.146:8083"
      KAFKA_CLUSTERS_1_SCHEMAREGISTRY: "http://172.17.23.146:8081"
      KAFKA_CLUSTERS_1_KSQLDBSERVER: "http://172.17.23.146:8088"

      KAFKA_CLUSTERS_2_NAME: lab2
      KAFKA_CLUSTERS_2_BOOTSTRAPSERVERS: ${BOOTSTRAP_SERVERS_LAB02}
      KAFKA_CLUSTERS_2_METRICS_PORT: 9997
      KAFKA_CLUSTERS_2_KAFKACONNECT_0_NAME: lab2
      KAFKA_CLUSTERS_2_KAFKACONNECT_0_ADDRESS: "http://172.17.26.178:8083"
      KAFKA_CLUSTERS_2_SCHEMAREGISTRY: "http://172.17.26.178:8081"
      KAFKA_CLUSTERS_2_KSQLDBSERVER: "http://172.17.26.178:8088"


      KAFKA_CLUSTERS_3_NAME: bigdata
      KAFKA_CLUSTERS_3_BOOTSTRAPSERVERS: ${BOOTSTRAP_SERVERS_LAB03}
      KAFKA_CLUSTERS_3_METRICS_PORT: 9997

    secrets:
          - LDAP_ADMIN_PASSWORD





secrets:
  SUPERNOVA_MASTER_USER:
    external: true
  SUPERNOVA_SLAVE_USER:
    external: true
  SUPERNOVA_PASS:
    external: true
  RHODRY_USER:
    external: true
  RHODRY_PASS:
    external: true
  BILOG_USER:
    external: true
  BILOG_PASS:
    external: true
  RABBIT_PASS:
    external: true
  LDAP_ADMIN_PASSWORD:
    external: true
  KAFKA_JAAS_2024-08-18:
    external: true
  

networks:
  rhodry:
    external: true

volumes:
  dglab:
