version: "3.9"

networks:
  platform:
    external: true

x-network: &network
  networks:
    - platform

x-healthcheck-config: &healthcheck-config
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 40s

x-deploy-on-front: &deploy-on-front
  deploy:
    replicas: 1
    placement:
      constraints:
        - node.hostname == ${HOSTNAME_01}

x-deploy-on-host-01: &deploy-on-host-01
  deploy:
    placement:
      constraints:
        - node.hostname == ${HOSTNAME_01}
x-deploy-on-host-02: &deploy-on-host-02
  deploy:
    placement:
      constraints:
        - node.hostname == ${HOSTNAME_02}
x-deploy-on-host-03: &deploy-on-host-03
  deploy:
    placement:
      constraints:
        - node.hostname == ${HOSTNAME_03}
        
##################################################################

services:
  api:
    image: ${API_IMAGE}
    ports:
      - ${API_PORT}:80
    environment:
      TZ: Asia/Tehran
      ASPNETCORE_ENVIRONMENT: Production
      AUTH_JWT_KEY: sample_keyASdasdasd2341231213123123vsvdfg
      AUTH_JWT_ISSUER: dataplatform.com
      AUTH_JWT_AUDIENCE: dataplatform
      AUTH_MINUTES_TO_EXPIRE: 2880
      LDAP_SERVER: 172.20.65.42
      LDAP_PORT: 636
      LDAP_SEARCH_DN: "cn=admin,dc=dataplatform,dc=com"
      LDAP_SEARCH_DN_PASS: adminpassword
      MONGO_CONSTRING: mongodb://admin:admin@172.20.65.42:27017
      MONGO_DB: api
      SQL_API_USER: api
      SQL_API_PASS: Sh!@%%^567
      SQL_API_UNMASKED_USER: api
      SQL_API_UNMASKED_PASS: Sh!@%%^567
      SQL_LOG_USERNAME: api
      SQL_LOG_PASSWORD: Sh!@%%^567
      SQL_LOG_SERVER: 172.20.65.42
      SQL_LOG_DATABASE: DW
      SQL_LOG_SCHEMA_NAME: api
      SQL_LOG_TABLE_NAME: api_log
      ELASTICSEARCH_ADDRESS: http://172.20.65.42:9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: elasticpassword
      DOCKER_SOCKET_URI: unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    configs:
      - source: api-settings
        target: /app/appsettings.json
    <<: [*network, *deploy-on-front]

configs:
  api-settings:
    file: ./app/src/appsettings.json
