
services:

  influxdb:
    image: ${INFLUXDB_IMAGE}
    ports:
      - ${INFLUXDB_PORT}:8086
    volumes:
       - influxdb-data:/var/lib/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: influxdb
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb_password
      DOCKER_INFLUXDB_INIT_ORG: DataPlatform
      DOCKER_INFLUXDB_INIT_BUCKET: defaultBucket
      # DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE=/run/secrets/influxdb2-admin-token 
    <<: [*network, *deploy-on-front]
    # healthcheck:
    #   test: ["CMD", "pg_isready", "-U", "postgres", "-h", "localhost", "-p", "5432"]
    #   <<: *healthcheck-config

  chronograf:
    image: ${CHRONOGRAF_IMAGE}
    ports:
      - ${CHRONOGRAF_PORT}:8888
    volumes:
      - chronograf-data:/var/lib/chronograf
    # environment:
      # INFLUXDB_URL: http://influxdb:8086
      # INFLUXDB_USERNAME: admin
      # INFLUXDB_PASSWORD: admin111
    <<: [*network, *deploy-on-front]
    # healthcheck:
    #   test: ["CMD", "pg_isready", "-U", "postgres", "-h", "localhost", "-p", "5432"]
    #   <<: *healthcheck-config

  kapacitor:
    image: ${KAPACITOR_IMAGE}
    ports:
      - ${KAPACITOR_PORT}:9092
    volumes: 
      - kapacitor-data:/var/lib/kapacitor
    configs:
      - source: kapacitor-config
        target: /etc/kapacitor/kapacitor.conf
    <<: [*network, *deploy-on-front]
    # healthcheck:
    #   test: ["CMD", "pg_isready", "-U", "postgres", "-h", "localhost", "-p", "5432"]
    #   <<: *healthcheck-config

  telegraf:
    image: ${TELEGRAF_IMAGE}
    configs:
      - source: telegraf-config
        target: /etc/telegraf/telegraf.conf
    <<: [*network, *deploy-on-front]
    # healthcheck:
    #   test: ["CMD", "pg_isready", "-U", "postgres", "-h", "localhost", "-p", "5432"]
    #   <<: *healthcheck-config

secrets:
  influxdb_password:
    external: true

volumes:
  influxdb-data:
  chronograf-data:
  kapacitor-data:

configs:
  telegraf-config:
    file: ./config/telegraf.conf
  kapacitor-config:
    file: ./config/kapacitor.conf
